### ISSUE TITLE
FR带反馈

### ISSUE THREAD

**Issue by A2Sumie** [idol-bbq-utils/idol-bbq-utils#11]
环境Debian12/amd64/双Zen1核+8g+ssd
X Premium（但蓝勾“认证中”不知道是不是10000推文/日的限制）
Docker-compose配置
配置文件贴后面了（高度依赖claude）

坏消息是日志没好好存sro

FR：
1.B站的错误处理
B站蛮容易出操作频繁的错误，而且一报就是几条一起，看不出interval_time在起作用
另外还有特殊字符（审核？）的错误，重试也不会有用，希望有回避措施
（比如来一条xxx在y时发送了一条推特，但转发失败了之类的？）
2. 部署初始化
刚加进去的账号会被转发很多不是最新的推文
希望可以配置在某个绝对时间（比如2024.12.16 1800+9）之前不转发任何东西只构建数据库，或者其他的调试模式

反馈
1. docker镜像里好像没有gallery-dl
2. 感觉不只有1000/天 10000/天的限制🤔Reply感觉特别容易挂。不知道具体的窗口和机制，反正加interval或者临时下线也能缓解（retry等待也许再放大一些好？）
3. 完全没蓝勾前转发了一些2020的推文不知道什么情况

以下配置
```
bots:
  - name: 'NijiBeacon'
    websites:
      # Sally配置 - 白天黄金时段
      - domain: 'https://x.com'
        paths: ['sally_amaki']
        cookie_file: '/app/assets/cookies/xcookies.txt'
        config:
          cron: '*/3 10-23 * * *'  # 10-23点每2分钟
          interval_time:
            max: 5000
            min: 2000
          media:
            type: 'no-storage'
            gallery_dl:
              path: '/usr/local/bin/gallery-dl'
              cookie_file: '/app/assets/cookies/xcookies.txt'

      # Sally配置 - 凌晨时段
      - domain: 'https://x.com'
        paths: ['sally_amaki']
        cookie_file: '/app/assets/cookies/xcookies.txt'
        config:
          cron: '*/5 0-1 * * *'  # 0-1点每3分钟
          interval_time:
            max: 5000
            min: 2000
          media:
            type: 'no-storage'
            gallery_dl:
              path: '/usr/local/bin/gallery-dl'
              cookie_file: '/app/assets/cookies/xcookies.txt'

      # Sally配置 - 深夜时段
      - domain: 'https://x.com'
        paths: ['sally_amaki']
        cookie_file: '/app/assets/cookies/xcookies.txt'
        config:
          cron: '*/12 2-9 * * *'  # 2-9点每10分钟
          interval_time:
            max: 5000
            min: 2000
          media:
            type: 'no-storage'
            gallery_dl:
              path: '/usr/local/bin/gallery-dl'
              cookie_file: '/app/assets/cookies/xcookies.txt'

      # 主要成员组 - 白天
      - domain: 'https://x.com'
        paths: ['227_staff', 'nao_aikawa227', 'mao_asaoka227', 'emma_tsukishiro', 'kawase_uta_0227',
                'ui_sakura_0526', 'chiharu_okr', 'satsuki_shiina', 'luna_shijo227', 
                'rino_mochizuki', 'nagomi_saijo', 'kura_maru_maru', 'ru_ri0808', 
                'hinagaurara', 'ainacchi_35', '227keisanchu', 'nemunemu_753', 'sitakke_uta']
        cookie_file: '/app/assets/cookies/xcookies.txt'
        config:
          cron: '*/7 8-23 * * *'  # 白天每5分钟
          interval_time:
            max: 5000
            min: 2000
          media:
            type: 'no-storage'
            gallery_dl:
              path: '/usr/local/bin/gallery-dl'
              cookie_file: '/app/assets/cookies/xcookies.txt'

      # 主要成员组 - 夜间
      - domain: 'https://x.com'
        paths: ['227_staff', 'nao_aikawa227', 'mao_asaoka227', 'emma_tsukishiro', 'kawase_uta_0227',
                'ui_sakura_0526', 'chiharu_okr', 'satsuki_shiina', 'luna_shijo227', 
                'rino_mochizuki', 'nagomi_saijo', 'kura_maru_maru', 'ru_ri0808', 
                'hinagaurara', 'ainacchi_35', '227keisanchu', 'nemunemu_753', 'sitakke_uta']
        cookie_file: '/app/assets/cookies/xcookies.txt'
        config:
          cron: '*/20 0-7 * * *'  # 夜间每15分钟
          interval_time:
            max: 5000
            min: 2000
          media:
            type: 'no-storage'
            gallery_dl:
              path: '/usr/local/bin/gallery-dl'
              cookie_file: '/app/assets/cookies/xcookies.txt'

      # 角色账号组 - 白天
      - domain: 'https://x.com'
        paths: ['_fujimasakura', '_kiryutouko', '_ichinosehotaru', '_serahonoka', 
                '_takigawamiu', '_saitonicole', '_oriharasumika', '_himuromizuki', '_nishiurasora']
        cookie_file: '/app/assets/cookies/xcookies.txt'
        config:
          cron: '*/30 8-23 * * *'  # 白天每30分钟
          interval_time:
            max: 5000
            min: 2000
          media:
            type: 'no-storage'
            gallery_dl:
              path: '/usr/local/bin/gallery-dl'
              cookie_file: '/app/assets/cookies/xcookies.txt'

      # 角色账号组 - 夜间
      - domain: 'https://x.com'
        paths: ['_fujimasakura', '_kiryutouko', '_ichinosehotaru', '_serahonoka', 
                '_takigawamiu', '_saitonicole', '_oriharasumika', '_himuromizuki', '_nishiurasora']
        cookie_file: '/app/assets/cookies/xcookies.txt'
        config:
          cron: '0 */2 0-7 * * *'  # 夜间每2小时
          interval_time:
            max: 5000
            min: 2000
          media:
            type: 'no-storage'
            gallery_dl:
              path: '/usr/local/bin/gallery-dl'
              cookie_file: '/app/assets/cookies/xcookies.txt'

    forward_to:
      - type: 'bilibili'
        token: '$$$'
        bili_jct: '$$$'
    config:
      user_agent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36'
      interval_time:
        max: 9000
        min: 4000
      media:
        type: 'no-storage'
        gallery_dl:
          path: '/usr/local/bin/gallery-dl'
          cookie_file: '/app/assets/cookies/xcookies.txt'

```

**Comment by ChocoLZS** [comment]
## FR
1. `interval_time` 在之前的设想中主要是给爬虫用的，让爬虫特征没那么明显🤔（指被程序检测），但可能这块还得再想想怎么做。
    **操作频繁** 可能是因为一开始建库的时候转发了大量推文导致too many requests，telegram这里也是一样的，可以结合第二点一起修复。
   错误处理这块，因为考虑到多平台转发的兼容问题，我偷懒了。之后看看怎么做。
2. 加入todo


## 反馈

> 1. docker镜像里好像没有gallery-dl
> 2. 感觉不只有1000/天 10000/天的限制🤔Reply感觉特别容易挂。不知道具体的窗口和机制，反正加interval或者临时下线也能缓解（retry等待也许再放大一些好？）
> 3. 完全没蓝勾前转发了一些2020的推文不知道什么情况
> 

1. docker镜像这里的 gallery-dl ，因为预想中不知道用户是否会启用这个功能，所以这部分需要用户自动安装。之后可能会添加all-in-one的docker镜像之类的
3. reply容易挂具体是指什么呢？reply无法抓取？超过时间限制？还是因为抓取推文过多账号被限制查看了？
4. 理论上来说这个无头浏览器能看见的推文是和有登录态的账号看到的推文是一致的，不过我以前也发现过偶尔转发过旧推文，可能跟推特的推荐有关，无法控制。

    > 转发了一些2020的推文

     如果只转发旧推文，新推文不转发，可能是因为cookie没有设置正确？

------------------

以下是我的配置参考：
Ubuntu 22.04.1 LTS / amd64 / Intel(R) Xeon(R) CPU E5-2697 v2 @ 2.70GHz 8核 / 4G

运行超10天没有重启过，重启是因为需要换翻译模型

机器只运行此docker的情况下
待机内存占用为600MB：没有任务
最高占用内存接近1G：有两个爬虫同时在开启网页标签页进行推文爬取

**docker-compose.yaml**
```yaml
services:
  forwarder:
    image: ghcr.io/idol-bbq-utils/idol-bbq-utils:latest
    container_name: 'forwarder'
    network_mode: 'host'
    restart: 'on-failure'
    environment:
      - TZ=Asia/Shanghai
      #- NO_SANDBOX=true
    volumes:
      - './assets/config.yaml:/app/config.yaml'
      - './assets/data.db:/app/data.db'
      - './assets:/app/assets'
      - '/tmp:/tmp'
```

**config.yaml**
```yaml
bots:
  - name: '莲-bot'
    websites:                                 # (required) websites to forward tweets from
      - domain: 'https://x.com'              # (required) website domain, notice the slash at the end
        paths: ['hanamiya_nina', 'NozomiNirei', 'sakuraihi_na', 'KonaTsukine', 'kannkannna', 'kurusurindesu', 'ssk_ktk828', 'cocona_nonaka', 'Hayama_Fuka']
        cookie_file: ./assets/choco-cookies.txt
        config:
          cron: '*/10 0-11 * * *'
      - domain: 'https://x.com'
        paths: ['hanamiya_nina', 'NozomiNirei', 'sakuraihi_na', 'KonaTsukine', 'kannkannna', 'kurusurindesu', 'ssk_ktk828', 'cocona_nonaka', 'Hayama_Fuka']
        cookie_file: ./assets/iizz-cookies.txt
        config:
          cron: '*/10 12-23 * * *'
      - domain: 'https://x.com'
        task_type: 'follows'
        task_title: '【莲团声优推特粉丝变化情况】'
        paths: ['hanamiya_nina', 'NozomiNirei', 'ssk_ktk828', 'cocona_nonaka', 'KonaTsukine', 'kannkannna', 'sakuraihi_na', 'Hayama_Fuka', 'kurusurindesu']
        config:
          cron: '5 23 * * *'
          interval_time:
            max: 0
            min: 0
          translator:
            type: 'none'
    forward_to:                               # (not required) forward to multiple platforms, you can add more than one
      - type: 'telegram'                      # (required) forward type
        token: '$$$'   # (required) telegram bot token
        chat_id: '$$$'
      - type: 'bilibili'
        token: '$$$'
        bili_jct: '$$$'
      - type: 'qq'
        token: '$$$'
        group_id: '$$$'
        url: 'http://localhost:33333'
    config:                                  # (not required) forwarder configurations
      user_agent:  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36 Edg/126.0.0.0'                 # (not required) puppeteer supported user agent
      interval_time:
        max: 4000
        min: 1000
      media:
        type: 'no-storage'
        gallery_dl:
          path: './assets/gallery-dl.bin'
          cookie_file: './assets/oishi-cookies.txt'
      translator:
        type: 'gemini'
        key:  '$$$'
        prompt: '现在你是一个翻译，接下来会给你日语或英语或者其它（大部分是日语和英语，有可能有埃及象形文字），请翻译以下日语或英语或其它为简体中文，只输出译文，不要输出原文。如果是带有# hash tag的标签、emoji、颜文字，不需要翻译，直接输出原文。如果无法翻译请输出：“╮(╯-╰)╭非常抱歉无法翻译”。此外，你不需要提供注解，只用翻译原文就行。'
  - name: '莲对手团-bot'
    websites:
      - domain: 'https://x.com'
        paths: ['amane_bushi', '_mmiya_mm']
        cookie_file: ./assets/shizuku-cookies.txt
        config:
          cron: '*/10 * * * *'
      - domain: 'https://x.com'
        task_type: 'follows'
        task_title: '【（待定）推特粉丝变化情况】'
        paths: ['amane_bushi', '_mmiya_mm']
        config:
          cron: '5 23 * * *'
    forward_to:
      - type: 'telegram'
        token: '$$$'
        chat_id: '$$$'
      - type: 'bilibili'
        token: '$$$'
        bili_jct: '$$$'
    config:
      media:
        type: 'no-storage'
        gallery_dl:
          path: './assets/gallery-dl.bin'
          cookie_file: './assets/shizuku-cookies.txt'
      translator:
        type: 'gemini'
        key: '$$$'
      interval_time:
        max: 0
        min: 0
  - name: 'lovelive-follows-bot'
    websites:
      - domain: 'https://x.com'
        task_type: 'follows'
        task_title: '【星团声优推特粉丝变化情况】'
        paths: ['SayuriDate', 'Liyu0109', '_Naomi_Payton_', 'AoyamaNagisa', 'MisakiNako_', 'NozomiSuzuhara', 'AyaEmori_BOX', 'a_yabushima', '0927_yuina', 'Sakakura_Sakura']
        config:
          cron: '6 23 * * *'
      - domain: 'https://x.com'
        task_type: 'follows'
        task_title: '【虹团声优推特粉丝变化情况】'
        paths: ['yano_hinaki35', 'aguri_onishi', 'tomori_kusunoki', 'cocohayashi515', 'kaor1n_n', 'MayuSgr',  'kitoakari_1016', 'sashide_m', 't_chiemi1006', 'natyaaaaaaan07', 'iRis_k_miyu', 'k_moeka_', 'uchida_shu0524', 'homoto_akina']
        config:
          cron: '7 23 * * *'
      - domain: 'https://x.com'
        task_type: 'follows'
        task_title: '【水团声优推特粉丝变化情况】'
        paths: ['anju_inami', 'Rikako_Aida', 'suwananaka', 'box_komiyaarisa', 'Saito_Shuka', 'aikyan_', 'Kanako_tktk', 'aina_suzuki723', 'furihata_ai']
        config:
          cron: '8 23 * * *'
      - domain: 'https://x.com'
        task_type: 'follows'
        task_title: '【缪斯声优推特粉丝变化情况】'
        paths: ['nittaemi85', 'nanjolno', 'aya_uchida', 'mimori_suzuko', 'rippialoha', 'pile_eric', 'kusudaaina', 'INFO_shikaco', 'tokui_sorangley']
        config:
          cron: '9 23 * * *'
    forward_to:                               # (not required) forward to multiple platforms, you can add more than one
      - type: 'telegram'                      # (required) forward type
        token: '$$$'   # (required) telegram bot token
        chat_id: '$$$'
      - type: 'bilibili'
        token: '$$$'
        bili_jct: '$$$'
    config:
      interval_time:
        max: 0
        min: 0
```
