### ISSUE TITLE
FR：更多平台的订阅？

### ISSUE THREAD

**Issue by A2Sumie** [idol-bbq-utils/idol-bbq-utils#17]
莲空也有🐰的ins直播了（
所以fr一下ins/tiktok/youtube的推送（x

**Comment by ChocoLZS** [comment]
计划中，但目前要打算重构下数据存储，因为我发现X可以直接从接口中获取数据并进行存储。
之后会breaking change

**Comment by ChocoLZS** [comment]
目前在这个pr中进行了大重构（全部都是breaking），支持了ins转发 #16 

爬虫和消息转发解耦，后续会写一个在线doc文档

但得等我先 写完文本转图片的新feature，如果想体验新版的话可以参考我的最新使用的配置文件

不过数据库还是需要手动生成一下，后续会做自动化生成数据库的检查操作。

**新建数据库操作**

```bash
pnpm lerna run --scope=@idol-bbq-utils/tweet-forwarder generate
```

新建数据库的时长取决于推文翻译

此外爬虫默认设置的是只允许转发30分钟以内的最新推文，这个可以修改

-----------------

<details>
<summary>v0.2.x 的配置文件be like (这是实际在生产环境上运行的配置)</summary>

```yaml
crawlers:
  - name: '莲文章-上午-cb'
    origin: 'https://x.com'
    paths: ['hanamiya_nina', 'NozomiNirei', 'sakuraihi_na']
    cfg_crawler:
      cron: '*/10 0-11 * * *'
      cookie_file: ./assets/000-cookies.txt
  - name: '莲文章-上午-dc'
    origin: 'https://x.com'
    paths: ['ssk_ktk828', 'cocona_nonaka', 'Hayama_Fuka']
    cfg_crawler:
      cron: '*/10 0-11 * * *'
      cookie_file: ./assets/000-cookies.txt
  - name: '莲文章-上午-mcp'
    origin: 'https://x.com'
    paths: ['KonaTsukine', 'kannkannna', 'kurusurindesu']
    cfg_crawler:
      cron: '*/10 0-11 * * *'
      cookie_file: ./assets/000-cookies.txt
  - name: '莲文章-下午-cb'
    origin: 'https://x.com'
    paths: ['hanamiya_nina', 'NozomiNirei', 'sakuraihi_na']
    cfg_crawler:
      cron: '*/10 12-23 * * *'
      cookie_file: ./assets/111-cookies.txt
  - name: '莲文章-下午-dc'
    origin: 'https://x.com'
    paths: ['ssk_ktk828', 'cocona_nonaka', 'Hayama_Fuka']
    cfg_crawler:
      cron: '*/10 12-23 * * *'
      cookie_file: ./assets/111-cookies.txt
  - name: '莲文章-下午-mcp'
    origin: 'https://x.com'
    paths: ['KonaTsukine', 'kannkannna', 'kurusurindesu']
    cfg_crawler:
      cron: '*/10 12-23 * * *'
      cookie_file: ./assets/111-cookies.txt
  
  - name: '拉拉-上午'
    origin: 'https://x.com'
    paths: ['_mmiya_mm', 'amane_bushi', '_asainanami']
    cfg_crawler:
      cron: '*/12 0-7 * * *'
      cookie_file: ./assets/333-cookies.txt
  - name: '拉拉-中午'
    origin: 'https://x.com'
    paths: ['_mmiya_mm', 'amane_bushi', '_asainanami']
    cfg_crawler:
      cron: '*/12 8-15 * * *'
      cookie_file: ./assets/444-cookies.txt
  - name: '拉拉-下午'
    origin: 'https://x.com'
    paths: ['_mmiya_mm', 'amane_bushi', '_asainanami']
    cfg_crawler:
      cron: '*/12 16-23 * * *'
      cookie_file: ./assets/222-cookies.txt
  - name: '虹-上午'
    origin: 'https://x.com'
    paths: ['yano_hinaki35', 'aguri_onishi', 'tomori_kusunoki', 'cocohayashi515', 'kaor1n_n', 'MayuSgr',  'kitoakari_1016', 'sashide_m', 't_chiemi1006', 'natyaaaaaaan07', 'iRis_k_miyu', 'k_moeka_', 'uchida_shu0524', 'homoto_akina']
    cfg_crawler:
      cron: '4-59/12 0-7 * * *'
      cookie_file: ./assets/333-cookies.txt
  - name: '虹-中午'
    origin: 'https://x.com'
    paths: ['yano_hinaki35', 'aguri_onishi', 'tomori_kusunoki', 'cocohayashi515', 'kaor1n_n', 'MayuSgr',  'kitoakari_1016', 'sashide_m', 't_chiemi1006', 'natyaaaaaaan07', 'iRis_k_miyu', 'k_moeka_', 'uchida_shu0524', 'homoto_akina']
    cfg_crawler:
      cron: '4-59/12 8-15 * * *'
      cookie_file: ./assets/444-cookies.txt
  - name: '虹-下午'
    origin: 'https://x.com'
    paths: ['yano_hinaki35', 'aguri_onishi', 'tomori_kusunoki', 'cocohayashi515', 'kaor1n_n', 'MayuSgr',  'kitoakari_1016', 'sashide_m', 't_chiemi1006', 'natyaaaaaaan07', 'iRis_k_miyu', 'k_moeka_', 'uchida_shu0524', 'homoto_akina']
    cfg_crawler:
      cron: '4-59/12 16-23 * * *'
      cookie_file: ./assets/222-cookies.txt
  
  - name: '莲粉丝'
    origin: 'https://x.com'
    paths: ['hanamiya_nina', 'NozomiNirei', 'ssk_ktk828', 'cocona_nonaka', 'KonaTsukine', 'kannkannna', 'sakuraihi_na', 'Hayama_Fuka', 'kurusurindesu']
    task_type: 'follows'
    cfg_crawler:
      cron: '6/20 * * * *'
  - name: '莲对手团粉丝'
    origin: 'https://x.com'
    paths: ['_mmiya_mm', 'amane_bushi']
    task_type: 'follows'
    cfg_crawler:
      cron: '6/20 * * * *'
  - name: '星粉丝'
    origin: 'https://x.com'
    paths: ['SayuriDate', 'Liyu0109', '_Naomi_Payton_', 'AoyamaNagisa', 'MisakiNako_', 'NozomiSuzuhara', 'AyaEmori_BOX', 'a_yabushima', '0927_yuina', 'Sakakura_Sakura']
    task_type: 'follows'
    cfg_crawler:
      cron: '8/20 * * * *'
  - name: '虹粉丝'
    origin: 'https://x.com'
    paths: ['yano_hinaki35', 'aguri_onishi', 'tomori_kusunoki', 'cocohayashi515', 'kaor1n_n', 'MayuSgr',  'kitoakari_1016', 'sashide_m', 't_chiemi1006', 'natyaaaaaaan07', 'iRis_k_miyu', 'k_moeka_', 'uchida_shu0524', 'homoto_akina']
    task_type: 'follows'
    cfg_crawler:
      cron: '8/20 * * * *'
  - name: '水粉丝'
    origin: 'https://x.com'
    paths: ['anju_inami', 'Rikako_Aida', 'suwananaka', 'box_komiyaarisa', 'Saito_Shuka', 'aikyan_', 'Kanako_tktk', 'aina_suzuki723', 'furihata_ai']
    task_type: 'follows'
    cfg_crawler:
      cron: '7/20 * * * *'
  - name: '缪粉丝'
    origin: 'https://x.com'
    paths: ['nittaemi85', 'nanjolno', 'aya_uchida', 'mimori_suzuko', 'rippialoha', 'pile_eric', 'kusudaaina', 'INFO_shikaco', 'tokui_sorangley']
    task_type: 'follows'
    cfg_crawler:
      cron: '7/20 * * * *'
  - name: '其它粉丝'
    origin: 'https://x.com'
    paths: ['_asainanami', 'hasunosora_SIC']
    task_type: 'follows'
    cfg_crawler:
      cron: '9/20 * * * *'

  - name: '莲ins'
    origin: 'https://www.instagram.com'
    paths: ['miyake_miu_', 'nirei_nozomi_official', 'sasaki_kotoko828', 'ringring_rin']
    cfg_crawler:
      cron: '*/30 * * * *'
      cookie_file: ./assets/ins.txt
  - name: '莲ins粉丝'
    origin: 'https://www.instagram.com'
    paths: ['miyake_miu_', 'nirei_nozomi_official', 'sasaki_kotoko828', 'ringring_rin']
    task_type: 'follows'
    cfg_crawler:
      cron: '7-59/30 * * * *'
      cookie_file: ./assets/ins.txt

cfg_crawler:
  translator:
    provider: 'Deepseek'
    api_key: '$'
    cfg_translator:
      prompt: '现在你是一个翻译，接下来会给你日语或英语或者其它（大部分是日语和英语，有可能有埃及象形文字），请翻译以下日语或英语或其它为简体中文，只输出译文，不要输出原文。如果是带 有# hash tag的标签、emoji、颜文字，不需要翻译，直接输出原文。如果无法翻译请输出：“╮(╯-╰)╭非常抱歉无法翻译”。此外，你不需要提供注解，只用翻译原文就行。'
      extended_payload:
        temprature: 1.3

forwarders:  
  - name: '莲文章转发'
    origin: 'https://x.com'
    paths: ['hanamiya_nina', 'NozomiNirei', 'ssk_ktk828', 'cocona_nonaka', 'KonaTsukine', 'kannkannna', 'sakuraihi_na', 'Hayama_Fuka', 'kurusurindesu']
    subscribers: ["tg频道", "莲机械桑", "qq-少莲团", "qq-sukisuki"]
  
  - name: '虹文章转发'
    origin: 'https://x.com'
    paths: ['yano_hinaki35', 'aguri_onishi', 'tomori_kusunoki', 'cocohayashi515', 'kaor1n_n', 'MayuSgr',  'kitoakari_1016', 'sashide_m', 't_chiemi1006', 'natyaaaaaaan07', 'iRis_k_miyu', 'k_moeka_', 'uchida_shu0524', 'homoto_akina']
    subscribers: ["tg频道", "lovelive机械桑"]
  
  - name: '拉拉文章转发'
    origin: 'https://x.com'
    paths: ['amane_bushi', '_asainanami']
    subscribers: ["tg频道", "lovelive机械桑"]
  
  - name: '三宅美羽单独转发'
    websites: ['https://x.com/_mmiya_mm', 'https://www.instagram.com/miyake_miu_']
    subscribers: ["qq-sukisuki", "tg频道", "lovelive机械桑"]
  - name: 'dc家文章转发'
    origin: 'https://x.com'
    paths: ['ssk_ktk828', 'cocona_nonaka', 'Hayama_Fuka']
    subscribers: ['qq-sayazz']

  - name: '莲ins转发'
    origin: 'https://www.instagram.com'
    paths: ['nirei_nozomi_official', 'sasaki_kotoko828', 'ringring_rin']
    subscribers: ["tg频道", "莲机械桑", "qq-少莲团", "qq-sukisuki"]

  # 粉丝
  - name: '莲粉丝转发'
    origin: 'https://x.com'
    paths: ['hanamiya_nina', 'NozomiNirei', 'ssk_ktk828', 'cocona_nonaka', 'KonaTsukine', 'kannkannna', 'sakuraihi_na', 'Hayama_Fuka', 'kurusurindesu']
    task_type: 'follows'
    task_title: '【莲团声优推特粉丝变化情况】'
    subscribers: ["tg频道", "莲机械桑", "qq-少莲团", "qq-sukisuki"]
    cfg_forwarder:
      cron: '8 0 * * *'
  - name: 'dc家粉丝转发'
    origin: 'https://x.com'
    paths: ['ssk_ktk828', 'cocona_nonaka', 'Hayama_Fuka']
    task_type: 'follows'
    task_title: '【DC家推特粉丝变化情况】'
    subscribers: ["qq-sayazz"]
    cfg_forwarder:
      cron: '8 0 * * *'
  - name: '莲对手团粉丝转发'
    origin: 'https://x.com'
    paths: ['_mmiya_mm', 'amane_bushi']
    task_type: 'follows'
    task_title: '【莲对手团粉丝变化情况】'
    subscribers: ["tg频道", "莲机械桑", "qq-少莲团", "qq-sukisuki"]
    cfg_forwarder:
      cron: '8 0 * * *'
  - name: '星粉丝转发'
    origin: 'https://x.com'
    paths: ['SayuriDate', 'Liyu0109', '_Naomi_Payton_', 'AoyamaNagisa', 'MisakiNako_', 'NozomiSuzuhara', 'AyaEmori_BOX', 'a_yabushima', '0927_yuina', 'Sakakura_Sakura']
    task_type: 'follows'
    task_title: '【星团声优推特粉丝变化情况】'
    subscribers: ["tg频道", "lovelive机械桑"]
    cfg_forwarder:
      cron: '8 0 * * *'
  - name: '虹粉丝转发'
    origin: 'https://x.com'
    paths: ['yano_hinaki35', 'aguri_onishi', 'tomori_kusunoki', 'cocohayashi515', 'kaor1n_n', 'MayuSgr',  'kitoakari_1016', 'sashide_m', 't_chiemi1006', 'natyaaaaaaan07', 'iRis_k_miyu', 'k_moeka_', 'uchida_shu0524', 'homoto_akina']
    task_type: 'follows'
    task_title: '【虹团声优推特粉丝变化情况】'
    subscribers: ["tg频道", "lovelive机械桑"]
    cfg_forwarder:
      cron: '8 0 * * *'
  - name: '水粉丝转发'
    origin: 'https://x.com'
    paths: ['anju_inami', 'Rikako_Aida', 'suwananaka', 'box_komiyaarisa', 'Saito_Shuka', 'aikyan_', 'Kanako_tktk', 'aina_suzuki723', 'furihata_ai']
    task_type: 'follows'
    task_title: '【水团声优推特粉丝变化情况】'
    subscribers: ["tg频道", "lovelive机械桑"]
    cfg_forwarder:
      cron: '8 0 * * *'
  - name: '缪粉丝转发'
    origin: 'https://x.com'
    paths: ['nittaemi85', 'nanjolno', 'aya_uchida', 'mimori_suzuko', 'rippialoha', 'pile_eric', 'kusudaaina', 'INFO_shikaco', 'tokui_sorangley']
    task_type: 'follows'
    task_title: '【缪团声优推特粉丝变化情况】'
    subscribers: ["tg频道", "lovelive机械桑"]
    cfg_forwarder:
      cron: '8 0 * * *'


cfg_forwarder:
  cron: '*/2 * * * *'


forward_targets:
  - platform: 'telegram'
    id: "tg频道"
    cfg_platform:
      token: '$E'
      chat_id: "$"
  - platform: 'bilibili'
    id: "莲机械桑"
    cfg_platform:
      sessdata: "$"
      bili_jct: "$"
      replace_regex: [
          ['https?://([a-zA-Z0-9-]+\.)+[a-zA-Z0-9-]+(/[a-zA-Z0-9\-._~:/?#\[\]@!$&()*,;=+]*)?', '🌐🔗'],
          ['\b[a-zA-Z0-9.-]+\.(?:com|org|net|edu|gov|cn|uk|de|jp)\b', '🌐']
        ]
  - platform: 'bilibili' # lovelive机械桑
    id: 'lovelive机械桑'
    cfg_platform:
      sessdata: '$'
      bili_jct: '$'
      replace_regex: [
        ['https?://([a-zA-Z0-9-]+\.)+[a-zA-Z0-9-]+(/[a-zA-Z0-9\-._~:/?#\[\]@!$&()*,;=+]*)?', '🌐🔗'],
        ['\b[a-zA-Z0-9.-]+\.(?:com|org|net|edu|gov|cn|uk|de|jp)\b', '🌐']
      ]
  - platform: 'qq'
    id: 'qq-少莲团'
    cfg_platform:
      token: '$'
      group_id: '$'
      url: 'http://127.0.0.1:33333'
  - platform: 'qq'
    id: 'qq-sukisuki'
    cfg_platform:
      token: '$'
      group_id: '$'
      url: 'http://127.0.0.1:33333'
  - platform: 'qq'
    id: 'qq-sayazz'
    cfg_platform:
      token: '$'
      group_id: '$'
      url: 'http://127.0.0.1:33333'

cfg_forward_target:
  block_until: '1h'

```

</details>
